services:

  postgres:
    image: postgres:16-alpine
    container_name: eventshop-postgres
    environment:
      POSTGRES_USER: eventshop
      POSTGRES_PASSWORD: eventshop
      POSTGRES_DB: eventshop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:7-alpine
    container_name: eventshop-redis
    ports:
      - "6379:6379"


  rabbitmq:
    image: rabbitmq:3-management
    container_name: eventshop-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"


  order-service:
    build:
      context: ../eventshop-order-service
    container_name: eventshop-order-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - redis


  inventory-service:
    build:
      context: ../eventshop-inventory-service
    container_name: eventshop-inventory-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://eventshop:eventshop@postgres:5432/eventshop
    ports:
      - "3002:3002"
    depends_on:
      - postgres
      - rabbitmq
      - redis


  payment-service:
    build:
      context: ../eventshop-payment-service
    container_name: eventshop-payment-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      DATABASE_URL: postgresql://eventshop:eventshop@postgres:5432/eventshop
    depends_on:
      - postgres
      - rabbitmq

  notification-service:
    build:
      context: ../eventshop-notification-service
    container_name: eventshop-notification-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      - rabbitmq


  api-gateway:
    build:
      context: ../eventshop-api-gateway
    container_name: eventshop-api-gateway
    environment:
      PORT: 4000
      ORDER_SERVICE_URL: http://order-service:3001
      INVENTORY_SERVICE_URL: http://inventory-service:3002
      PAYMENT_SERVICE_URL: http://payment-service:3003
    ports:
      - "4000:4000"
    depends_on:
      - order-service
      - inventory-service


volumes:
  postgres_data: