services:

  # =====================================================
  # INFRASTRUCTURE
  # =====================================================

  order-postgres:
    image: postgres:16-alpine
    container_name: eventshop-order-postgres
    environment:
      POSTGRES_USER: eventshop
      POSTGRES_PASSWORD: eventshop
      POSTGRES_DB: eventshop
    ports:
      - "5435:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U eventshop -d eventshop"
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  inventory-postgres:
    image: postgres:16-alpine
    container_name: eventshop-inventory-postgres
    environment:
      POSTGRES_USER: eventshop
      POSTGRES_PASSWORD: eventshop
      POSTGRES_DB: eventshop
    ports:
      - "5434:5432"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U eventshop -d eventshop"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  payment-postgres:
    image: postgres:16-alpine
    container_name: eventshop-payment-postgres
    environment:
      POSTGRES_USER: eventshop
      POSTGRES_PASSWORD: eventshop
      POSTGRES_DB: eventshop
    ports:
      - "5433:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U eventshop -d eventshop"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7-alpine
    container_name: eventshop-redis
    ports:
      - "6379:6379"
    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  rabbitmq:
    image: rabbitmq:3-management
    container_name: eventshop-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test:
        [
          "CMD",
          "rabbitmq-diagnostics",
          "-q",
          "ping"
        ]
      interval: 5s
      timeout: 5s
      retries: 10


  # =====================================================
  # ORDER SERVICE
  # =====================================================

  order-service:
    build:
      context: ../eventshop-order-service
    container_name: eventshop-order-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://eventshop:eventshop@order-postgres:5432/eventshop
    ports:
      - "3001:3001"
    depends_on:
      order-postgres: 
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy


  # =====================================================
  # INVENTORY SERVICE
  # =====================================================

  inventory-service:
    build:
      context: ../eventshop-inventory-service
    container_name: eventshop-inventory-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://eventshop:eventshop@inventory-postgres:5432/eventshop
    ports:
      - "3002:3002"
    depends_on:
      inventory-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy


  # =====================================================
  # PAYMENT SERVICE
  # =====================================================

  payment-service:
    build:
      context: ../eventshop-payment-service
    container_name: eventshop-payment-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
      DATABASE_URL: postgresql://eventshop:eventshop@payment-postgres:5432/eventshop
    depends_on:
      payment-postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy


  # =====================================================
  # NOTIFICATION SERVICE
  # =====================================================

  notification-service:
    build:
      context: ../eventshop-notification-service
    container_name: eventshop-notification-service
    environment:
      RABBITMQ_URL: amqp://admin:admin@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy


  # =====================================================
  # API GATEWAY
  # =====================================================

  api-gateway:
    build:
      context: ../eventshop-api-gateway
    container_name: eventshop-api-gateway
    environment:
      PORT: 4000
      ORDER_SERVICE_URL: http://order-service:3001
      INVENTORY_SERVICE_URL: http://inventory-service:3002
    ports:
      - "4000:4000"
    depends_on:
      order-service:
        condition: service_started
      inventory-service:
        condition: service_started

  eventshop-web:
    build:
      context: ../eventshop-web
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:4000
    container_name: eventshop-web
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
# =======================================================
# VOLUMES
# =======================================================

volumes:

  inventory_postgres_data:

  payment_postgres_data:

  order_postgres_data: